TodoConstants = {
    TODO_CREATE: 'TODO_CREATE',
    TODO_COMPLETE: 'TODO_COMPLETE',
    TODO_UNDO_COMPLETE: 'TODO_UNDO_COMPLETE',
    TODO_UPDATE: 'TODO_UPDATE',
    TODO_ARCHIVE: 'TODO_ARCHIVE',
    TODO_DESTROY: 'TODO_DESTROY'
};

module.exports = TodoConstants;
